### PR TITLE
multiple Defs bug fix

### PR DESCRIPTION
**Pull request by aashishkuma**
Problem Statement:
krnlmon code isn't compiling on Fedora 33, works on ubuntu 20.04.
[ 42%] Building CXX object stratum/proto/gnmi/CMakeFiles/gnmi_proto.dir/__/__/__/pb.out/gnmi/gnmi.grpc.pb.cc.o
/usr/bin/ld: switchlink/CMakeFiles/switchlink_o.dir/switchlink_link.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_link.c:49: **multiple definition of** `g_default_vrf_h'; switchlink/CMakeFiles/switchlink_o.dir/switchlink_address.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_address.c:24: first defined here
[ 43%] Building CXX object stratum/proto/gnmi/CMakeFiles/gnmi_proto.dir/__/__/__/pb.out/gnmi/gnmi_ext.pb.cc.o
/usr/bin/ld: switchlink/CMakeFiles/switchlink_o.dir/switchlink_neigh.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_neigh.c:28: **multiple definition of** `g_default_bridge_h'; switchlink/CMakeFiles/switchlink_o.dir/switchlink_link.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_link.c:50: first defined here
/usr/bin/ld: switchlink/CMakeFiles/switchlink_o.dir/switchlink_neigh.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_neigh.c:27: **multiple definition of** `g_default_vrf_h'; switchlink/CMakeFiles/switchlink_o.dir/switchlink_address.c.o:/root/snagapat/mvlut/trial/networking-recipe/krnlmon/krnlmon/switchlink/switchlink_address.c:24: first defined here

Analysis:
Gcc version on fedora 33 is higher than 10, and the default behavior of gcc has changed with respect to tentative definitions.

Fix:
Adding the global variables required for the test execution, in the test file of that particular file instead of the source code file.

### CODE REVIEW

**Review by ffoulkes — CHANGES_REQUESTED** [review]
`g_default_vrf_h` is a kernel monitor variable, not a test variable. You cannot move its defining instance into the tests. That will break kernel monitor itself.

I provided a local definition in `switchlink_link_test` because the unit under test did include the source file that containing the global definition. It was therefore safe (and necessary) for me to provide a definition. This is exactly equivalent to my providing local definitions of the global functions I was dummying.

You need to follow the same pattern.

Only define the variable in your test if you get an unresolved external reference to it.

Only use the variable if it is part of the test path (i.e., the functions under test require it). This includes resetting the variable to zero. (You should not initialize or reset variables that are not used in the test path.

**Comment by aashishkuma** [comment]
> `g_default_vrf_h` is a kernel monitor variable, not a test variable. You cannot move its defining instance into the tests. That will break kernel monitor itself.
> 
> The most straightforward solution is to refactor the defining instances into a common source file that can be shared between krnlmon and the unit tests.
> 
> See https://github.com/ipdk-io/krnlmon/pull/44/files.



> `g_default_vrf_h` is a kernel monitor variable, not a test variable. You cannot move its defining instance into the tests. That will break kernel monitor itself.
> 
> The most straightforward solution is to refactor the defining instances into a common source file that can be shared between krnlmon and the unit tests.
> 
> See https://github.com/ipdk-io/krnlmon/pull/44/files.

No it will not break krnlmon. While creating the switchlink_o library, it would still refer to the global variable defined in switchlink_link.c as they are part of the same compilation unit. The only difference would come when we try to create a test executable, it would take the value of g_default_vrf_h from the test file which is fine, because in a test environment we can simulate how we want the global variables to be. The other approach was to include the switchlink_link.c file in testing.cmake for all the test executables, but that approach doesn't look good to me because of the added dependency.

**Comment by ffoulkes** [comment]
The correct solution to the problem is to refactor the variables in question into a separate module that can be included where needed.

**Comment by aashishkuma** [comment]
Taken care by the below commit:
https://github.com/ipdk-io/krnlmon/pull/44
